"""Story CRUD and versioning routes."""

from fastapi import FastAPI, Request, Query
from typing import Optional, Any
import os
import re
import subprocess
import sys
import tempfile
import yaml
import logging
from src.models.story_models import _load_yaml_with_includes, describe_connection_graph_status

logger = logging.getLogger(__name__)
_GENERATED_GRAPH_COMMENT = (
    "# WARNING: The fields below are generated by the connection-graph compile step.\n"
    "# Do not edit them manually; re-run tools/compile_connections.py instead.\n"
)

# Only allow alphanumeric, underscores, and hyphens in story IDs
_SAFE_STORY_ID_RE = re.compile(r'^[a-zA-Z0-9_-]+$')


def _sanitize_story_id(story_id: str) -> Optional[str]:
    """Sanitize a story ID to prevent path traversal.
    
    Returns the sanitized ID, or None if the ID is invalid.
    """
    story_id = story_id.replace(" ", "_").lower()
    story_id = os.path.basename(story_id)
    if not story_id or not _SAFE_STORY_ID_RE.match(story_id):
        return None
    return story_id


def _get_version_dir(base_dir: str, story_id: str) -> str:
    """Get the version backup directory for a story.
    
    Uses a persistent project directory instead of /tmp so that
    version history survives reboots.
    """
    version_dir = os.path.join(base_dir, "story_versions", story_id)
    os.makedirs(version_dir, exist_ok=True)
    return version_dir


def _dump_story_yaml(story_data: Any) -> str:
    yaml_data = yaml.dump(story_data, allow_unicode=True, sort_keys=False)
    if "connection_graph_source_md5:" not in yaml_data:
        return yaml_data
    return yaml_data.replace(
        "connection_graph_source_md5:",
        f"{_GENERATED_GRAPH_COMMENT}connection_graph_source_md5:",
        1,
    )


def register_story_routes(app: FastAPI, story_manager: Any):
    """Register story-related routes on the FastAPI app.
    
    Args:
        app: The FastAPI application.
        story_manager: The story manager instance.
    """

    saves_dir = getattr(story_manager, 'saves_dir', None) or os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__)))),
        "saves"
    )

    def _resolve_story_path(story_id: str, temp_path: Optional[str] = None) -> Optional[str]:
        if temp_path:
            real_temp = os.path.realpath(temp_path)
            if os.path.commonpath([real_temp, tempfile.gettempdir()]) != tempfile.gettempdir():
                return None
            if os.path.exists(real_temp):
                return real_temp
            return None
        return story_manager.get_story_path(story_id)
    
    @app.get("/api/stories")
    async def get_stories():
        """Get list of all available stories."""
        stories = story_manager.discover_stories()
        return [{
            "id": s['id'],
            "title": s['title'],
            "name": s.get('name', s['title']),
            "author": s.get('author', 'Unknown'),
            "description": s.get('description', '')
        } for s in stories]

    @app.get("/api/story/{story_id}")
    async def get_story(story_id: str, temp_path: Optional[str] = Query(None)):
        """Get a story by ID, optionally from a temporary path.
        
        Supports multi-file stories with 'includes' directives —
        included files are merged before returning to the editor.
        """
        path_to_read = _resolve_story_path(story_id, temp_path)

        if not path_to_read or not os.path.exists(path_to_read):
            return {"error": "Story not found" if not temp_path else "Temporary file not found."}
        
        try:
            story_data = _load_yaml_with_includes(path_to_read)
        except Exception as e:
            logger.error(f"Error loading story {story_id} with includes: {e}")
            with open(path_to_read, "r", encoding="utf-8") as f:
                story_data = yaml.safe_load(f)

        story_data.update(describe_connection_graph_status(story_data))
        return story_data

    @app.post("/api/story/{story_id}/compile-connections")
    async def compile_story_connections(story_id: str, request: Request):
        """Compile and optionally write the story connection graph."""
        body = await request.json()
        temp_path = body.get("temp_path")
        with_llm = bool(body.get("with_llm"))

        path_to_read = _resolve_story_path(story_id, temp_path)
        if not path_to_read or not os.path.exists(path_to_read):
            return {"error": "Story not found" if not temp_path else "Temporary file not found."}

        tool_path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__)))),
            "tools",
            "compile_connections.py",
        )
        command = [sys.executable, tool_path, path_to_read, "--write"]
        if with_llm:
            command.append("--with-llm")

        try:
            subprocess.run(command, check=True, capture_output=True, text=True)
            story_data = _load_yaml_with_includes(path_to_read)
            story_data.update(describe_connection_graph_status(story_data))
            return {
                "success": True,
                "story": story_data,
            }
        except subprocess.CalledProcessError as exc:
            logger.error("Error compiling connections for %s: %s", story_id, exc.stderr or exc.stdout)
            return {"error": (exc.stderr or exc.stdout or str(exc)).strip()}

    @app.post("/api/story")
    async def create_story(request: Request):
        """Create a new story."""
        json_data = await request.json()
        raw_id = json_data.get("id")
        if not raw_id:
            return {"error": "Story ID is required"}

        story_id = _sanitize_story_id(raw_id)
        if not story_id:
            return {"error": "Invalid story ID. Use only letters, numbers, underscores, and hyphens."}

        story_path = story_manager.get_story_path(story_id)
        if story_path and os.path.exists(story_path):
            return {"error": "Story with this ID already exists"}

        try:
            if 'isNew' in json_data:
                del json_data['isNew']
            
            json_data['id'] = story_id

            yaml_data = _dump_story_yaml(json_data)
            
            new_story_path = os.path.join(story_manager.stories_dir, f"{story_id}.yaml")
            with open(new_story_path, "w", encoding="utf-8") as f:
                f.write(yaml_data)
            
            return {"success": True, "story_id": story_id}
        except Exception as e:
            logger.error(f"Error creating story {story_id}: {e}")
            return {"error": str(e)}

    @app.post("/api/story/{story_id}")
    async def save_story(story_id: str, request: Request):
        """Save a story to a YAML file with version backup."""
        story_id = _sanitize_story_id(story_id)
        if not story_id:
            return {"error": "Invalid story ID."}

        story_path = story_manager.get_story_path(story_id)
        if not story_path:
             story_path = os.path.join(story_manager.stories_dir, f"{story_id}.yaml")
        
        json_data = await request.json()
        
        try:
            version_dir = _get_version_dir(saves_dir, story_id)
            
            existing_versions = [f for f in os.listdir(version_dir) if f.endswith('.yaml')]
            next_version = len(existing_versions)
            
            if os.path.exists(story_path):
                backup_path = os.path.join(version_dir, f"{story_id}_{next_version}.yaml")
                with open(story_path, "r", encoding="utf-8") as src:
                    with open(backup_path, "w", encoding="utf-8") as dst:
                        dst.write(src.read())
                logger.info(f"Created backup version {next_version} for story {story_id}")
            
            yaml_data = _dump_story_yaml(json_data)
            with open(story_path, "w", encoding="utf-8") as f:
                f.write(yaml_data)
            
            if hasattr(story_manager, 'invalidate_cache'):
                story_manager.invalidate_cache()
                
            return {"success": True, "version": next_version}
        except Exception as e:
            logger.error(f"Error saving story {story_id}: {e}")
            return {"error": str(e)}

    @app.post("/api/story/{story_id}/backup-original")
    async def backup_original(story_id: str):
        """Backup the original story file when first loaded (version 0)."""
        story_id = _sanitize_story_id(story_id)
        if not story_id:
            return {"error": "Invalid story ID."}

        story_path = story_manager.get_story_path(story_id)
        if not story_path or not os.path.exists(story_path):
            return {"error": "Story not found"}
        
        try:
            version_dir = _get_version_dir(saves_dir, story_id)
            original_path = os.path.join(version_dir, f"{story_id}_0.yaml")
            
            if not os.path.exists(original_path):
                with open(story_path, "r", encoding="utf-8") as src:
                    with open(original_path, "w", encoding="utf-8") as dst:
                        dst.write(src.read())
                logger.info(f"Created original backup (version 0) for story {story_id}")
                return {"success": True, "created": True}
            
            return {"success": True, "created": False}
        except Exception as e:
            logger.error(f"Error backing up original for story {story_id}: {e}")
            return {"error": str(e)}

    @app.get("/api/story/{story_id}/versions")
    async def get_versions(story_id: str):
        """Get list of available versions for a story."""
        story_id = _sanitize_story_id(story_id)
        if not story_id:
            return {"error": "Invalid story ID."}

        try:
            version_dir = _get_version_dir(saves_dir, story_id)
            
            versions = []
            for f in os.listdir(version_dir):
                if f.endswith('.yaml'):
                    file_path = os.path.join(version_dir, f)
                    stat = os.stat(file_path)
                    version_num = int(f.replace(f"{story_id}_", "").replace(".yaml", ""))
                    versions.append({
                        "version": version_num,
                        "filename": f,
                        "timestamp": stat.st_mtime,
                        "size": stat.st_size
                    })
            
            versions.sort(key=lambda x: x["version"])
            return {"versions": versions}
        except Exception as e:
            logger.error(f"Error getting versions for story {story_id}: {e}")
            return {"error": str(e)}

    @app.get("/api/story/{story_id}/version/{version}")
    async def get_version(story_id: str, version: int):
        """Get content of a specific version."""
        story_id = _sanitize_story_id(story_id)
        if not story_id:
            return {"error": "Invalid story ID."}

        try:
            version_dir = _get_version_dir(saves_dir, story_id)
            version_path = os.path.join(version_dir, f"{story_id}_{version}.yaml")
            
            if not os.path.exists(version_path):
                return {"error": f"Version {version} not found"}
            
            with open(version_path, "r", encoding="utf-8") as f:
                story_data = yaml.safe_load(f)
            return story_data
        except Exception as e:
            logger.error(f"Error getting version {version} for story {story_id}: {e}")
            return {"error": str(e)}

    @app.post("/api/story/{story_id}/restore/{version}")
    async def restore_version(story_id: str, version: int):
        """Restore a story to a specific version."""
        story_id = _sanitize_story_id(story_id)
        if not story_id:
            return {"error": "Invalid story ID."}

        story_path = story_manager.get_story_path(story_id)
        if not story_path:
            return {"error": "Story not found"}
        
        try:
            version_dir = _get_version_dir(saves_dir, story_id)
            version_path = os.path.join(version_dir, f"{story_id}_{version}.yaml")
            
            if not os.path.exists(version_path):
                return {"error": f"Version {version} not found"}
            
            existing_versions = [f for f in os.listdir(version_dir) if f.endswith('.yaml')]
            next_version = len(existing_versions)
            backup_path = os.path.join(version_dir, f"{story_id}_{next_version}.yaml")
            
            with open(story_path, "r", encoding="utf-8") as src:
                with open(backup_path, "w", encoding="utf-8") as dst:
                    dst.write(src.read())
            
            with open(version_path, "r", encoding="utf-8") as src:
                with open(story_path, "w", encoding="utf-8") as dst:
                    dst.write(src.read())
            
            logger.info(f"Restored story {story_id} to version {version}")
            return {"success": True, "backed_up_as": next_version}
        except Exception as e:
            logger.error(f"Error restoring version {version} for story {story_id}: {e}")
            return {"error": str(e)}

