#!/usr/bin/env python
"""Compile structural and optional semantic story connections."""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path
from typing import Any, Dict, Iterable, List

import yaml
from openai import OpenAI

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.models.story_models import (  # noqa: E402
    Connection,
    Story,
    _load_yaml_with_includes,
    compute_connection_graph_source_md5,
    load_story_from_file,
)

GENERATED_SECTION_COMMENT = (
    "# WARNING: The fields below are generated by the connection-graph compile step.\n"
    "# Do not edit them manually; re-run tools/compile_connections.py instead.\n"
)


def load_local_env() -> None:
    try:
        from dotenv import load_dotenv
    except ImportError:
        return

    search_paths = [
        Path.cwd() / ".env",
        PROJECT_ROOT / ".env",
    ]

    for path in search_paths:
        if path.exists():
            load_dotenv(path)
            return


def slugify(value: str) -> str:
    text = re.sub(r"[^a-zA-Z0-9]+", "_", value.strip()).strip("_").lower()
    return text or "connection"


def make_connection_id(source: str, semantic_key: str, targets: Iterable[str]) -> str:
    joined_targets = "_".join(sorted(set(targets)))
    return slugify(f"{source}_{semantic_key}_{joined_targets}")


def connection_entry(
    source: str,
    targets: List[str],
    *,
    semantic_key: str = "related",
    connection_id: str | None = None,
) -> Dict[str, Any]:
    normalized_targets: List[str] = []
    seen_targets = set()
    for target in targets:
        if not isinstance(target, str) or not target or target == source or target in seen_targets:
            continue
        seen_targets.add(target)
        normalized_targets.append(target)

    if not source or not normalized_targets:
        return {}

    return {
        "id": connection_id or make_connection_id(source, semantic_key, normalized_targets),
        "source": source,
        "targets": normalized_targets,
    }


def dedupe_connections(connections: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    deduped: Dict[str, Dict[str, Any]] = {}
    for conn in connections:
        if not isinstance(conn, dict):
            continue
        normalized = connection_entry(
            str(conn.get("source") or ""),
            list(conn.get("targets") or []),
            semantic_key=str(conn.get("id") or "related"),
            connection_id=str(conn.get("id") or "") or None,
        )
        if not normalized:
            continue
        validated = Connection(**normalized).model_dump()
        deduped[validated["id"]] = validated
    return list(deduped.values())


def extract_deterministic_connections(story: Story) -> List[Dict[str, Any]]:
    connections: List[Dict[str, Any]] = []

    def extract_node_mentions_from_definition(text: str, source_node_id: str) -> List[str]:
        # TODO: Expand this exact-ID matcher into natural-language edge inference so the
        # compiler can infer links from prose even when authors do not mention node IDs
        # verbatim in definitions.
        if not text:
            return []

        targets: List[str] = []
        seen = set()

        for target_node_id in story.nodes.keys():
            if target_node_id == source_node_id:
                continue

            pattern = rf"(?<![A-Za-z0-9_]){re.escape(target_node_id)}(?![A-Za-z0-9_])"
            if re.search(pattern, text) and target_node_id not in seen:
                seen.add(target_node_id)
                targets.append(target_node_id)

        return targets

    for node_id, node in story.nodes.items():
        object_ids = [obj.id for obj in node.objects if obj.id]
        if object_ids:
            connections.append(connection_entry(
                node_id,
                object_ids,
                semantic_key="contains_local_objects",
            ))

        authored_targets = extract_node_mentions_from_definition(node.definition, node_id)
        if authored_targets:
            connections.append(connection_entry(
                node_id,
                authored_targets,
                semantic_key="definition_node_mentions",
            ))

        for action in node.actions or []:
            for effect in action.effects:
                if effect.type == "goto_node" and effect.target:
                    connections.append(connection_entry(
                        node_id,
                        [effect.target],
                        semantic_key=f"goto_{action.id or 'action'}",
                    ))

    for char in story.characters or []:
        placement_targets = sorted({
            value for value in [
                char.properties.get("location"),
                char.properties.get("location_id"),
            ]
            if isinstance(value, str) and value
        })
        if placement_targets:
            connections.append(connection_entry(
                char.id,
                placement_targets,
                semantic_key="located_at_nodes",
            ))

    for obj in story.objects or []:
        contained_ids = [item for item in obj.properties.get("contains", []) if isinstance(item, str)]
        if contained_ids:
            connections.append(connection_entry(
                obj.id,
                contained_ids,
                semantic_key="contains_items",
            ))

    for node in story.nodes.values():
        for obj in node.objects:
            contained_ids = [item for item in obj.properties.get("contains", []) if isinstance(item, str)]
            if contained_ids:
                connections.append(connection_entry(
                    obj.id,
                    contained_ids,
                    semantic_key="contains_items",
                ))

    return dedupe_connections(connections)


def build_semantic_prompt(story: Story, deterministic_connections: List[Dict[str, Any]]) -> str:
    entity_chunks: List[str] = []

    for node_id, node in story.nodes.items():
        chunk = [f"NODE {node_id}: {node.name or node_id}"]
        if node.definition:
            chunk.append(f"Definition: {node.definition[:800]}")
        if node.explicit_state:
            chunk.append(f"Explicit state: {node.explicit_state[:400]}")
        if node.implicit_state:
            chunk.append(f"Implicit state: {node.implicit_state[:400]}")
        entity_chunks.append("\n".join(chunk))

    for char in story.characters or []:
        chunk = [f"CHARACTER {char.id}: {char.name}"]
        if char.definition:
            chunk.append(f"Definition: {char.definition[:800]}")
        if char.memory:
            chunk.append(f"Memory: {' | '.join(char.memory[:5])}")
        entity_chunks.append("\n".join(chunk))

    for obj in story.objects or []:
        chunk = [f"OBJECT {obj.id}: {obj.name}"]
        if obj.definition:
            chunk.append(f"Definition: {obj.definition[:800]}")
        entity_chunks.append("\n".join(chunk))

    entities_blob = "\n\n".join(entity_chunks)

    return (
        "You are extracting semantic propagation edges for an AI native text based game engine.\n"
        "Return strict JSON only with a top-level key `connections`.\n"
        "Each connection must contain: id, source, targets.\n"
        "Rules:\n"
        "- Encode the edge meaning in the id itself using a short, distinguishable snake_case phrase.\n"
        "- Only propose edges that help world-state propagation or consistency.\n"
        "- Do not repeat obvious structural edges already covered by deterministic extraction.\n"
        "- targets must be a non-empty array of entity IDs.\n\n"
        f"Existing deterministic edges:\n{json.dumps(deterministic_connections, ensure_ascii=False, indent=2)}\n\n"
        f"Story entities:\n\n{entities_blob}"
    )


def extract_semantic_connections(story: Story, deterministic_connections: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    load_local_env()

    api_key = os.getenv("LLM_API_KEY")
    base_url = os.getenv("LLM_BASE_URL")
    model = os.getenv("LLM_MODEL") or os.getenv("LLM_MODEL_NAME")
    if not api_key or not base_url or not model:
        raise RuntimeError("LLM_API_KEY, LLM_BASE_URL, and LLM_MODEL (or LLM_MODEL_NAME) are required for --with-llm")

    client = OpenAI(api_key=api_key, base_url=base_url)
    prompt = build_semantic_prompt(story, deterministic_connections)
    completion = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": "Return strict JSON only."},
            {"role": "user", "content": prompt},
        ],
        temperature=0.2,
        response_format={"type": "json_object"},
    )
    content = completion.choices[0].message.content or "{}"
    parsed = json.loads(content)
    semantic_connections = parsed.get("connections", []) if isinstance(parsed, dict) else []
    if not isinstance(semantic_connections, list):
        return []
    return dedupe_connections([conn for conn in semantic_connections if isinstance(conn, dict)])


def merge_compiled_with_manual(existing_connections: List[Dict[str, Any]], compiled_connections: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    # TODO: Replace this additive merge with diff-based cleanup once compile provenance is tracked.
    preserved = [
        conn for conn in existing_connections
        if isinstance(conn, dict)
        and not any(field in conn for field in ("description", "bidirectional", "origin"))
    ]
    return dedupe_connections([*preserved, *compiled_connections])


def compile_story_connections(story_path: str, *, with_llm: bool = False) -> Dict[str, Any]:
    story = load_story_from_file(story_path)
    if story_path.endswith((".yaml", ".yml")):
        merged_story_data = _load_yaml_with_includes(story_path)
    else:
        with open(story_path, "r", encoding="utf-8") as handle:
            merged_story_data = json.load(handle)

    deterministic = extract_deterministic_connections(story)
    compiled = list(deterministic)
    if with_llm:
        compiled.extend(extract_semantic_connections(story, deterministic))

    existing_connections = merged_story_data.get("connections") or []
    merged_connections = merge_compiled_with_manual(existing_connections, dedupe_connections(compiled))

    return {
        "connection_graph_source_md5": compute_connection_graph_source_md5(merged_story_data),
        "connections": merged_connections,
    }


def format_connections_yaml(payload: Dict[str, Any]) -> str:
    body = yaml.safe_dump(
        payload,
        sort_keys=False,
        allow_unicode=True,
        width=100,
    )
    if "connection_graph_source_md5:" not in body:
        return body
    return body.replace("connection_graph_source_md5:", f"{GENERATED_SECTION_COMMENT}connection_graph_source_md5:", 1)


def write_connection_graph(story_path: str, payload: Dict[str, Any]) -> None:
    story_file = Path(story_path)
    suffix = story_file.suffix.lower()

    if suffix in {".yaml", ".yml"}:
        with open(story_file, "r", encoding="utf-8") as handle:
            raw_story = yaml.safe_load(handle) or {}
        raw_story.pop("connection_graph_source_md5", None)
        raw_story.pop("connections", None)
        raw_story["connection_graph_source_md5"] = payload["connection_graph_source_md5"]
        raw_story["connections"] = payload["connections"]
        with open(story_file, "w", encoding="utf-8") as handle:
            handle.write(format_connections_yaml(raw_story))
        return

    if suffix == ".json":
        with open(story_file, "r", encoding="utf-8") as handle:
            raw_story = json.load(handle)
        raw_story["connection_graph_source_md5"] = payload["connection_graph_source_md5"]
        raw_story["connections"] = payload["connections"]
        with open(story_file, "w", encoding="utf-8") as handle:
            json.dump(raw_story, handle, ensure_ascii=False, indent=2)
        return

    raise ValueError("Unsupported file format. Use YAML or JSON.")


def main() -> int:
    parser = argparse.ArgumentParser(description="Compile structural and semantic story connections.")
    parser.add_argument("story_path", help="Path to a story YAML or JSON file")
    parser.add_argument("--with-llm", action="store_true", help="Use the configured LLM to suggest semantic connections")
    parser.add_argument("--write", action="store_true", help="Write connection_graph_source_md5 and connections back to the story file")
    args = parser.parse_args()

    payload = compile_story_connections(args.story_path, with_llm=args.with_llm)
    if args.write:
        write_connection_graph(args.story_path, payload)

    sys.stdout.write(format_connections_yaml(payload))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
